services:
  mysql:
    image: mysql:8.0
    container_name: web-chat-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_chat
    volumes:
      - ./docker/mysql:/var/lib/mysql
